### ISSUE TITLE
Details for configuration the schema.json

### ISSUE THREAD

**Issue by dawic-33** [Threagile/threagile#7]
Hello everyone, i have some problems to configure the schema. i get a message from intelij that the schema could not be downloaded due to a 403 error. Besides that i am not sure how to import the schema.json to the Threagile schema in the Youtube video. Is there a detailed description?
Many thanks in advance

**Comment by cschneider4711** [comment]
Thx for the ticket.

**Here are some details/guides (esp. for IntelliJ):**
- Download the JSON Schema file and save it locally somewhere 
- Open a threagile YAML file you want to a associate the schema with
- Click in IntelliJ in the lower right edge where "No JSON schema" is given as default.

**When this is the first time "registering" the Threagile schema:**
- Click the top-most popup-entry **"+ New Schema Mapping..."** and choose the downloaded schema file _(this is only required one time initially for your IDE to "learn" about the Threagile schema)_.

**On all occasions when editing another/new/not-yet-edited Threagile YAML file:**
- Click in IntelliJ in the lower right edge where "No JSON schema" is given as default and choose the "Threagile schema" form the popup menu (registered above initially) to associate that very YAML file with the schema.

**Comment by cschneider4711** [comment]
Closed the ticket... But of course, in case of any questions, feel free to ask here...  ;)

**Comment by cschneider4711** [comment]
BTW: Also try out the live-editing templates from https://run.threagile.io/live-templates.txt with intros about how to add them to your IDEs in it. ;)

**Comment by GeHorst** [comment]
@cschneider4711 Sorry to ask, how do you add the templates to GoLand/IntelliJ?

And you mentioned that for Visual Studio Code to be able to use the schema there was something to me changed in the file to be able to use it. Would be cool to find that documented here too.
