### ISSUE TITLE
Feature Request: Show line number on error of model validation

### ISSUE THREAD

**Issue by mum-viadee** [Threagile/threagile#8]
Currently I tried to use threagile and created a model form the stub. When I try to execute threagile on that model I get the following error: 

`Parsing model: /app/work/threagile-model.yaml
2020/11/13 09:59:42 Unknown 'machine' of technical asset: 
Unknown 'machine' of technical asset: `

I have a few technical assets in my model, so it would be handy to get the line number of the model file in the error message.

**Comment by cschneider4711** [comment]
Yep, absolutely! 

Taking more detailed model validation/error handling into account is very important. Delivering more detailed error handling in terms of line numbers and/or asset names is in the queue. With this ticket we now have a nice way to track it.

Keep posting more feature requests, as this seeds the most pressing issues that should be addressed! ;)

**Comment by cschneider4711** [comment]
Now the response returns more detailed content of where inside the model the problem was detected.
