### ISSUE TITLE
PDF report graphs have no status data

### ISSUE THREAD

**Issue by mcolledge91** [Threagile/threagile#83]
![image (2)](https://github.com/Threagile/threagile/assets/37017393/7b64dcbb-becb-40bb-b4d7-1924ee5a6c7c)

![image](https://github.com/Threagile/threagile/assets/37017393/29e418b6-289d-4733-a15d-931e18915b35)

In this example I have, for example, 16 'Accepted' status risks showing in the excel report.

**Comment by CMon** [comment]
I figured out the same for my reports, same for the coloring of the chapters which should turn to less warning colors if all risks are mitigated but they stay the same, something inside the model is broken.

**Comment by CMon** [comment]
I have a working fix for this but it is currently based upon my other pull request #87 if its urgent you could find it inside my fork

**Comment by CMon** [comment]
ok I added the pull request that should fix this issue, see: #98

**Comment by CMon** [comment]
@mcolledge91 could you check against the current master if this problem still exists?

**Comment by ezavgorodniy** [comment]
On behalf of Max I can confirm that it's fixed 
![image](https://github.com/user-attachments/assets/39459c07-7c83-4c47-9f58-63f3fe62923b)
